/*

    /*
 Auto-generated by: https://github.com/pmndrs/gltfjsx
 */

    import React, { useRef } from 'react'
    import { useGLTF } from '@react-three/drei'

    export function Model(props) {
        const { nodes, materials } = useGLTF(`${import.meta.env.BASE_URL}models/mixer_01.glb`)
        return (
            <group {...props} dispose={null}>
                <group position={[0, 0.001, -0.168]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.chasisbody.geometry}
                        material={materials['Off White Plastic Glossy']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.chasistapa.geometry}
                        material={materials['Steel - Satin.004']}
                    />
                    <group position={[-0.018, 0.063, 0.019]} rotation={[-3.141, Math.PI / 2, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.componentestop.geometry}
                            material={materials['Black Plastic']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.componentestop_1.geometry}
                            material={materials['Rubber pattern']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.componentestop_2.geometry}
                            material={materials['Grippy Rubber Material']}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.ledsrojo.geometry}
                        material={materials['Glass Red.001']}
                        position={[0, 0, 0.049]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.ledsverde.geometry}
                        material={materials['Glass green']}
                        position={[0, 0, 0.049]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.leversmetal.geometry}
                        material={materials['Brushed used metal silver']}
                        position={[-0.021, 0.03, 0.031]}
                        rotation={[3.089, 0, -Math.PI / 2]}
                        scale={0.01}
                    />
                    <group position={[0, 0, 0.049]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <group position={[45, 0, 15]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.blD.geometry}
                                material={materials['Piano Finish']}
                                scale={10}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.blP.geometry}
                                material={materials['White Plastic']}
                                scale={10}
                            />
                        </group>
                        <group position={[45, 0, -15]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.bmD.geometry}
                                material={materials['Piano Finish']}
                                scale={10}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.bmP.geometry}
                                material={materials['White Plastic']}
                                scale={10}
                            />
                        </group>
                        <group position={[-45, 0, -15]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.cmD.geometry}
                                material={materials['Piano Finish']}
                                scale={10}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.cmP.geometry}
                                material={materials['White Plastic']}
                                scale={10}
                            />
                        </group>
                        <group position={[-45, 0, 15]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.cdD.geometry}
                                material={materials['Piano Finish']}
                                scale={10}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.cdP.geometry}
                                material={materials['White Plastic']}
                                scale={10}
                            />
                        </group>
                        <group position={[0, 0, 30]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.dgD.geometry}
                                material={materials['Piano Finish']}
                                scale={10}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.dgP.geometry}
                                material={materials['White Plastic']}
                                scale={10}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.masterD.geometry}
                            material={materials['Piano Finish']}
                            scale={10}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.masterP.geometry}
                            material={materials['White Plastic']}
                            scale={10}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seridotsmasterorange.geometry}
                        material={materials['Translucent procedural orange plastic']}
                        position={[0, 0, 0.049]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    />
                    <group position={[0, -0.06, 0.018]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.seripianoblack_1.geometry}
                            material={nodes.seripianoblack_1.material}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.seripianoblack_2.geometry}
                            material={materials['Piano Finish']}
                        />
                    </group>
                </group>
            </group>
        )
    }
useGLTF.preload(`${import.meta.env.BASE_URL}models/mixer_01.glb`)